"""empty message

Revision ID: 5e7f3ca144c4
Revises: 
Create Date: 2023-05-29 13:33:27.511275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e7f3ca144c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nationality')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('service_accounts',
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('account_no', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('verification_status', sa.Integer(), nullable=True),
    sa.Column('verified_date_utc', sa.DateTime(), nullable=True),
    sa.Column('verification_status_id', sa.String(), nullable=True),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_service_accounts_account_id'), 'service_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_service_accounts_account_no'), 'service_accounts', ['account_no'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_no', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('date_joined_utc', sa.DateTime(), nullable=False),
    sa.Column('user_account_status', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.Integer(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_date_joined_utc'), 'users', ['date_joined_utc'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_no'), 'users', ['user_no'], unique=True)
    op.create_table('account_kyc_profiles',
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('id_document_type', sa.String(length=100), nullable=True),
    sa.Column('id_date_of_issue', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['service_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number')
    )
    op.create_index(op.f('ix_account_kyc_profiles_id'), 'account_kyc_profiles', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('address_line', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['service_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('channels',
    sa.Column('channel_no', sa.String(), nullable=False),
    sa.Column('running_balance', sa.Float(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_no', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['service_accounts.account_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_channels_channel_no'), 'channels', ['channel_no'], unique=True)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_table('kyc_verification_status',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('verification_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=False),
    sa.Column('request_status', sa.String(length=200), nullable=True),
    sa.Column('status_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['service_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_kyc_verification_status_id'), 'kyc_verification_status', ['id'], unique=False)
    op.create_table('payment_accounts',
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('bank_branch', sa.String(), nullable=True),
    sa.Column('bank_swift_code', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('mpesa_account_number', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['service_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_accounts_id'), 'payment_accounts', ['id'], unique=False)
    op.create_table('user_account_memberships',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['service_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'user_id', 'id')
    )
    op.create_index(op.f('ix_user_account_memberships_id'), 'user_account_memberships', ['id'], unique=False)
    op.create_table('user_activation_status',
    sa.Column('user_activation_status_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activation_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('activation_reason', sa.String(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_activation_status_id', 'id')
    )
    op.create_index(op.f('ix_user_activation_status_activation_code'), 'user_activation_status', ['activation_code'], unique=False)
    op.create_index(op.f('ix_user_activation_status_id'), 'user_activation_status', ['id'], unique=False)
    op.create_index(op.f('ix_user_activation_status_user_activation_status_id'), 'user_activation_status', ['user_activation_status_id'], unique=False)
    op.create_table('user_login_infos',
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_infos_email_address'), 'user_login_infos', ['email_address'], unique=False)
    op.create_index(op.f('ix_user_login_infos_id'), 'user_login_infos', ['id'], unique=False)
    op.create_index(op.f('ix_user_login_infos_phone_number'), 'user_login_infos', ['phone_number'], unique=False)
    op.create_table('channel_invites',
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('invite_status', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_invites_id'), 'channel_invites', ['id'], unique=False)
    op.create_index(op.f('ix_channel_invites_invite_code'), 'channel_invites', ['invite_code'], unique=True)
    op.create_table('channel_participants',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'channel_id')
    )
    op.create_table('payment_requests',
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('request_status', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_edited_date_utc', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_requests_id'), 'payment_requests', ['id'], unique=False)
    op.create_index(op.f('ix_payment_requests_request_id'), 'payment_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_payment_requests_request_status'), 'payment_requests', ['request_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_requests_request_status'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_request_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_id'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_table('channel_participants')
    op.drop_index(op.f('ix_channel_invites_invite_code'), table_name='channel_invites')
    op.drop_index(op.f('ix_channel_invites_id'), table_name='channel_invites')
    op.drop_table('channel_invites')
    op.drop_index(op.f('ix_user_login_infos_phone_number'), table_name='user_login_infos')
    op.drop_index(op.f('ix_user_login_infos_id'), table_name='user_login_infos')
    op.drop_index(op.f('ix_user_login_infos_email_address'), table_name='user_login_infos')
    op.drop_table('user_login_infos')
    op.drop_index(op.f('ix_user_activation_status_user_activation_status_id'), table_name='user_activation_status')
    op.drop_index(op.f('ix_user_activation_status_id'), table_name='user_activation_status')
    op.drop_index(op.f('ix_user_activation_status_activation_code'), table_name='user_activation_status')
    op.drop_table('user_activation_status')
    op.drop_index(op.f('ix_user_account_memberships_id'), table_name='user_account_memberships')
    op.drop_table('user_account_memberships')
    op.drop_index(op.f('ix_payment_accounts_id'), table_name='payment_accounts')
    op.drop_table('payment_accounts')
    op.drop_index(op.f('ix_kyc_verification_status_id'), table_name='kyc_verification_status')
    op.drop_table('kyc_verification_status')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_no'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_account_kyc_profiles_id'), table_name='account_kyc_profiles')
    op.drop_table('account_kyc_profiles')
    op.drop_index(op.f('ix_users_user_no'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_date_joined_utc'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_accounts_account_no'), table_name='service_accounts')
    op.drop_index(op.f('ix_service_accounts_account_id'), table_name='service_accounts')
    op.drop_table('service_accounts')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
